### ISSUE TITLE
Notes got an error: AppleEvent handler failed.

### ISSUE THREAD

**Issue by LeoK987** [mindfulsource/AppleNotes2Joplin#1] opened 2020-10-31 13:17 UTC
MacOS 10.15.7 (19H2)

**Comment by mindfulsource** [comment] 2020-10-31 14:24
I'm on exact same 19H2 Catalina. (Everything works at my end.)

I'd need more info to help, e.g. what line on the AppleScript does it highlight when error pops up?

**Comment by LeoK987** [comment] 2020-10-31 17:46
It doesn't highlight anything.  I ran it from the editor, it's my first time running a script on Mac, so it could be due to my ignorance.

See screen capture.

![Screen Shot 2020-10-31 at 6 40 25 PM](https://user-images.githubusercontent.com/6257601/97786048-19ba6100-1ba9-11eb-9c57-aaeb2e23b07b.png)

**Comment by mindfulsource** [comment] 2020-11-01 03:37
Cool, your screenshot shows a word highlighted in the applescript - "name" - underneath the pop-up, see it? (`name of folders`)

Another clue is where, in the script's actions in macOS, it stops. It already lets you set an export folder, right? Does it fail immediately after that, or after more stuff happens?

Have you read the entire instructions? Maybe you don't use an account called "iCloud" and that's why it can't bring up the list of folders.

Anyway I just updated script to clarify it's the list of folders *in the iCloud account* within Notes app, it might help. Can you:

1. Make sure you're having script specify your correct account name eg. "iCloud" or "On My Mac" or another like "Gmail" (and tell me whether you have multiple accounts).

2. Try this on the updated script code and let me know if works.

AppleScript is a bit murky, hope we can solve this for you. If you're following instructions fully, could be something else entirely. Catalina has bugs but I'm using exact same Catalina as you. ¯\_(ツ)_/¯

**Comment by LeoK987** [comment] 2020-11-01 04:11
Thank you.  Just checked with Notes, my accounts include "iCloud", "On My Mac" and "Gmail".  Is that possibly causing the problem?  I will try your new script later.

**Comment by LeoK987** [comment] 2020-11-01 04:23
With the new script, the error occurs after I choose a folder from Notes.

![Screen Shot 2020-11-01 at 5 22 15 AM](https://user-images.githubusercontent.com/6257601/97795101-6aaa7380-1c02-11eb-920b-6b3ba6eb5f46.png)

**Comment by mindfulsource** [comment] 2020-11-01 04:53
Good, we're making progress. (Error further down the script means it gets further through the process without error.) Must be because you have 3 accounts there but at my end I only have one iCloud account. I think I just need more additions (like the one I added an hour ago) to specify which account, for all the steps.

Let me emulate having those 3 types of accounts and see if I can reproduce, then fix it accordingly. 👍

**Comment by mindfulsource** [comment] 2020-11-01 05:03
OK that was easy! Was as I suspected, script updated and tested works. I'll close this issue but do comment again if still not working. Any other problems create an issue.

**Closed by mindfulsource** 2020-11-01 05:03 UTC

**Comment by LeoK987** [comment] 2020-11-01 05:52
Excellent.  all my folders on iCloud are now exported.  But it doesn't let me choose gmail folders and folders on this mac.

**Comment by mindfulsource** [comment] 2020-11-01 09:36
As readme says, in the script text you need to replace all instances of "iCloud" with "On My Mac" or "<the name of your gmail account>" to export those accounts' folders. I won't code in an ability to export notes of all accounts at once at this time.
